### ISSUE TITLE
fplot error plotting piecewise symbolic variable

### ISSUE THREAD

**Issue by NRJank** [gnu-octave/symbolic#1278] opened 2023-10-26 12:39 UTC
the following is valid in Matlab, but produces errors with Octave 8.3.0, symbolic package 3.1.1:

```
>> pkg load symbolic

>> syms x

>> y = piecewise(x<-2, -2)
y = (sym) {-2  for x < -2

>> fplot(y)
error: isalnum: not defined for class
error: called from
    fplot at line 110 column 11
```

**Comment by cbm755** [comment] 2023-10-26 16:27
Sort of a dupe of #215, which is a list of stuff we haven't implemented, but given that we have `ezplot` we should probably also do `fplot`.

**Closed** 2023-10-28 04:47 UTC
Labels: compat_smt
